[package]
name = "visual-grep"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27.2"
eframe = "0.27.2"
regex = "1"
rfd = "0.14.1"
walkdir = "2.3.1"
rayon = "1.5"
log = "0.4"
env_logger = "0.11.3"